name: photo_view_web
description: Photo View provides a gesture sensitive zoomable widget. PhotoView is largely used to show interacive images.
version: 0.3.3
author: Renan C. Araújo <renan@caraujo.me>
homepage: https://github.com/renancaraujo/photo_view

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  build_runner: ^1.5.0
  build_web_compilers: ^2.0.0
  build_daemon: 1.0.0

dependency_overrides:
  flutter_web:
    #    git:
    #      url: https://github.com/flutter/flutter_web
    path: /Users/zhenxi/env/flutter_web/packages/flutter_web
  flutter_web_ui:
    #    git:
    #      url: https://github.com/flutter/flutter_web
    path: /Users/zhenxi/env/flutter_web/packages/flutter_web_ui

